apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bookmyvenue.fullname" . }}-secrets
  labels:
    {{- include "bookmyvenue.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.global.secrets.jwtSecret | b64enc | quote }}
  JWT_REFRESH_SECRET: {{ .Values.global.secrets.jwtRefreshSecret | b64enc | quote }}
  SMTP_USER: {{ .Values.global.secrets.smtpUser | b64enc | quote }}
  SMTP_PASS: {{ .Values.global.secrets.smtpPass | b64enc | quote }}
  STRIPE_SECRET_KEY: {{ .Values.global.secrets.stripeSecretKey | b64enc | quote }}
  STRIPE_WEBHOOK_SECRET: {{ .Values.global.secrets.stripeWebhookSecret | b64enc | quote }}
  RAZORPAY_KEY_ID: {{ .Values.global.secrets.razorpayKeyId | b64enc | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.global.secrets.razorpayKeySecret | b64enc | quote }}
