apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmyvenue.fullname" . }}-web
  labels:
    {{- include "bookmyvenue.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "bookmyvenue.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  type: ClusterIP
