apiVersion: v1
kind: Service
metadata:
  name: {{ include "bookmyvenue.fullname" . }}-owner
  labels:
    {{- include "bookmyvenue.labels" . | nindent 4 }}
    app.kubernetes.io/component: owner
spec:
  ports:
    - port: 3002
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    {{- include "bookmyvenue.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: owner
  type: ClusterIP
