apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmyvenue-config
  namespace: bookmyvenue
  labels:
    app.kubernetes.io/name: bookmyvenue
data:
  NODE_ENV: "production"
  PORT: "5000"
  WEB_PORT: "3000"
  ADMIN_PORT: "3001"
  OWNER_PORT: "3002"
  NEXT_PUBLIC_API_URL: "http://localhost/api/v1"
  MONGODB_URI: "mongodb://mongodb.bookmyvenue.svc.cluster.local:27017/bookmyvenue"
  REDIS_URL: "redis://redis.bookmyvenue.svc.cluster.local:6379"
