apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: database-policy
  namespace: bookmyvenue
spec:
  podSelector:
    matchLabels:
      app: bookmyvenue
      role: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bookmyvenue
          role: backend
    ports:
    - protocol: TCP
      port: 27017
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: bookmyvenue
spec:
  podSelector:
    matchLabels:
      app: bookmyvenue
      role: backend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: bookmyvenue
          role: frontend
    - podSelector:
        matchLabels:
          app.kubernetes.io/component: ingress
    ports:
    - protocol: TCP
      port: 5000
